export const data = {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      catagory: "Shirts",
      image: "/images/d1.jpg",
      brand: "Nike",
      price: 60,
      rating: 4,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      catagory: "Shirts",
      image: "/images/d1.jpg",
      brand: "Adidas",
      price: 30,
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
    },
    {
      _id: "3",
      name: "Pants",
      catagory: "Pants",
      image: "/images/d1.jpg",
      brand: "Puma",
      price: 80,
      rating: 3,
      numReviews: 10,
      countInStock: 3,
    },
  ],
};
